name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Scan for Secrets
        run: |
          git grep -e 'AWS_ACCESS_KEY_ID' -e 'AWS_SECRET_ACCESS_KEY' -e 'password' -- path/to/terraform/code
        continue-on-error: true


  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init -backend=false
        continue-on-error: true

      - name: Validate Terraform Configuration
        run: terraform validate -check-variables=false
        continue-on-error: true
