name: Terraform Code Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Validate Terraform code
        run: |
          terraform init -backend=false
          terraform validate
          terraform fmt -check -recursive

      - name: Check for exposed secrets
        run: |
          git grep -e 'AWS_ACCESS_KEY_ID' -e 'AWS_SECRET_ACCESS_KEY' -e 'password' -- '*.tf' || echo "No exposed secrets found."
      
      - name: Install Tfsec
        run: |
          curl -L "$(curl -s https://api.github.com/repos/tfsec/tfsec/releases/latest | grep -o -E "https://.+?tfsec-linux-amd64")" -o tfsec
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/
      
      - name: Scan with Tfsec
        run: tfsec .
