name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Scan for Secrets
        run: |
          git grep -e 'AWS_ACCESS_KEY_ID' -e 'AWS_SECRET_ACCESS_KEY' -e 'password' -- path/to/terraform/code
        continue-on-error: true

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  # Choose one of the following approaches for installing tfsec:

      # Option 1: Use a dedicated user with elevated privileges (recommended if possible)
      # - Create a dedicated user with write permissions to /usr/local/bin
      # - Update your workflow to use 'sudo -E' with that user for installation steps

      # Option 2: Install tfsec in a temporary directory (alternative)
      - name: Download tfsec (temporary directory)
        run: |
          LATEST=$(curl -s https://api.github.com/repos/tfsec/tfsec/releases/latest | grep -o -E "https://.+?tfsec-linux-amd64")
          curl -L "$LATEST" -o tfsec
          chmod +x tfsec

      - name: Run tfsec (use relative path if using temporary directory)
        run: ./tfsec .  # Adjust the path if using temporary directory

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init -backend=false
        continue-on-error: true

      - name: Validate Terraform Configuration
        run: terraform validate -check-variables=false
        continue-on-error: true
